//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.UIF.CONTRALAFT.Web.pages {
	
	
	public partial class listadoAcciones {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.ScriptManager ScriptManager1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtCodigoAccion;
		
		protected System.Web.UI.HtmlControls.HtmlTextArea txtAccion;
		
		protected System.Web.UI.HtmlControls.HtmlTextArea txtDescripcion;
		
		protected System.Web.UI.WebControls.GridView GridView1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtEditarCodigo;
		
		protected System.Web.UI.HtmlControls.HtmlTextArea txtEditarAccion;
		
		protected System.Web.UI.HtmlControls.HtmlTextArea txtEditarDescripcion;
		
		protected System.Web.UI.WebControls.Button btnSeleccionar;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtNombreIndicador;
		
		protected System.Web.UI.HtmlControls.HtmlTextArea txtDetalleIndicador;
		
		protected System.Web.UI.WebControls.DropDownList ddlCodigoAnho;
		
		protected System.Web.UI.UpdatePanel upSeccionEntidad;

		protected System.Web.UI.UpdatePanel upSeccionBotonIndicador; 

		protected System.Web.UI.HtmlControls.HtmlGenericControl divEntidad;
		
		protected System.Web.UI.WebControls.DropDownList ddlCodigoEntidad;
		
		protected System.Web.UI.WebControls.LinkButton IdBotonAgregarEntidad;
		
		protected System.Web.UI.UpdatePanel upListadoEntidades;
		
		protected System.Web.UI.WebControls.GridView GridView2;
		
		protected System.Web.UI.WebControls.Button btnSeleccionarIndicador;
		
		protected System.Web.UI.WebControls.Button btnNuevo;
		
		protected System.Web.UI.WebControls.Button btnInactive;
	}
}
